<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTqBAOkb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTqBAOkb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTqBAOkb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTqBAOkb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTqBAOkb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TqBAOkb',
    'container.build_id' => '98d55363',
    'container.build_time' => 1668005350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTqBAOkb');
